//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataneo.TutorialLibs.Domain.Translation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dataneo.TutorialLibs.Domain.Translation.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled at the request of the user.
        /// </summary>
        public static string CANCELED_BY_USER {
            get {
                return ResourceManager.GetString("CANCELED_BY_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty GUID.
        /// </summary>
        public static string EMPTY_GUID {
            get {
                return ResourceManager.GetString("EMPTY_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty parent folder id.
        /// </summary>
        public static string EMPTY_PARENT_FOLDER_ID {
            get {
                return ResourceManager.GetString("EMPTY_PARENT_FOLDER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty parent tutorial id.
        /// </summary>
        public static string EMPTY_PARENT_TUTORIAL_ID {
            get {
                return ResourceManager.GetString("EMPTY_PARENT_TUTORIAL_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty episode name.
        /// </summary>
        public static string EPISODE_NAME_EMPTY {
            get {
                return ResourceManager.GetString("EPISODE_NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episode name too short.
        /// </summary>
        public static string EPISODE_NAME_TO_SHORT {
            get {
                return ResourceManager.GetString("EPISODE_NAME_TO_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The episode length is too short.
        /// </summary>
        public static string EPISODE_TO_SHORT {
            get {
                return ResourceManager.GetString("EPISODE_TO_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extension not supported.
        /// </summary>
        public static string FILE_EXTENSION_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("FILE_EXTENSION_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size to small.
        /// </summary>
        public static string FILE_SIZE_TO_SMALL {
            get {
                return ResourceManager.GetString("FILE_SIZE_TO_SMALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name incorrect.
        /// </summary>
        public static string FILENAME_INCORECT {
            get {
                return ResourceManager.GetString("FILENAME_INCORECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid directory path.
        /// </summary>
        public static string INVALID_DIRECTORY {
            get {
                return ResourceManager.GetString("INVALID_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file path.
        /// </summary>
        public static string INVALID_FILE_PATH {
            get {
                return ResourceManager.GetString("INVALID_FILE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No child folders.
        /// </summary>
        public static string NO_FOLDERS {
            get {
                return ResourceManager.GetString("NO_FOLDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many directory levels.
        /// </summary>
        public static string TOO_MANY_DIRECTORY_LEVELS {
            get {
                return ResourceManager.GetString("TOO_MANY_DIRECTORY_LEVELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial name incorrent.
        /// </summary>
        public static string TUTORIAL_NAME_INCORECT {
            get {
                return ResourceManager.GetString("TUTORIAL_NAME_INCORECT", resourceCulture);
            }
        }
    }
}
