//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataneo.TutorialLibs.WPF.Translation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dataneo.TutorialLibs.WPF.Translation.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add tutorials from folder.
        /// </summary>
        public static string ADD_FOLDER {
            get {
                return ResourceManager.GetString("ADD_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add single tutorial.
        /// </summary>
        public static string ADD_SINGLE {
            get {
                return ResourceManager.GetString("ADD_SINGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoria.
        /// </summary>
        public static string CATEGORY {
            get {
                return ResourceManager.GetString("CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not watched.
        /// </summary>
        public static string NOT_WATCHED {
            get {
                return ResourceManager.GetString("NOT_WATCHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order by.
        /// </summary>
        public static string SORT {
            get {
                return ResourceManager.GetString("SORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order by date add.
        /// </summary>
        public static string SORT_BY_DATEADD {
            get {
                return ResourceManager.GetString("SORT_BY_DATEADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order by last visit.
        /// </summary>
        public static string SORT_BY_LASTVISIT {
            get {
                return ResourceManager.GetString("SORT_BY_LASTVISIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order by rating.
        /// </summary>
        public static string SORT_BY_RATING {
            get {
                return ResourceManager.GetString("SORT_BY_RATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order by title.
        /// </summary>
        public static string SORT_BY_TITLE {
            get {
                return ResourceManager.GetString("SORT_BY_TITLE", resourceCulture);
            }
        }
    }
}
